<?php declare(strict_types=1);

namespace AlecRabbit\Tests\Accessories;

use PHPUnit\Framework\TestCase;

class CallerDataTest extends TestCase
{
    /** @test */
    public function one(): void
    {
        $this->assertTrue(true);
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }
}
